# Generated by Django 3.2.14 on 2022-10-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='ScientistDetail',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
