# Generated by Django 3.2.14 on 2022-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceCenter', '0003_eventbooking_eventdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='event_recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
