# Generated by Django 3.2.14 on 2022-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceCenter', '0004_auto_20221002_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
