# Generated by Django 3.2.14 on 2022-10-02 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpaceCenter', '0005_auto_20221002_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('remark', models.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpaceCenter.eventdetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('attend_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attend_by_User', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpaceCenter.eventdetail')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_by_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
